# Generated by Django 4.2.1 on 2024-10-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact', models.IntegerField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
            ],
        ),
    ]
