# Generated by Django 4.2.1 on 2024-10-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfapp', '0003_alter_item_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
